### ISSUE TITLE
Wakatime browser plugin: unusual coding activity for 24 hours

### ISSUE THREAD

**Issue by dmig** [wakatime/chrome-wakatime#132]
I got an email telling that browser plugin is malfunctioning.

Plugin version: 2.0.1
Browser: Google Chrome 90.0.4430.212 (Official Build) (64-bit)

Other enabled extensions:
- daily.dev jlmpjdjjbgclbocgajdjefcidcncaied
- Gnome Shell integration gphhapmejobijbbhgpjhcjognlahblep
- Google Docs Offline ghbmnnjooekpmoecnnnilnnbdlolhkhi
- Google Mail Checker mihcahmgecmbnbcchbopgniflfhgnkff
- Google Translate aapbdbdomjkkjkaonfhkkikfgjllcleb
- Grammarly for Chrome kbfnbcaeplbcioakkpcpgfkobkghlhen
- JSON Viewer gbmdgpbipfallnflgajpaliibnhdgobh
- Picture-in-Picture Extension (by Google) hkgfoiooedgoejojocmhlaklaeopbecg
- The Great Discarder jlipbpadkjcklpeiajndiijbeieicbdh
- uBlock Origin cjpalhdlnbpafiamejdnhcphjbkeiagm

**Comment by funder7** [comment]
Hi, 
I'm noticing some strange behavior too, with browser activity on a specific project.

It happens only with this project: it's developed in php and javascript, in particular webpack dev server to test the JS part.

At the end of the day, I switch the PC into standby mode, leaving the page open in the browser, to resume the next morning.  (powered off - power led blinking)

I specified that it's based on webpack, because it's the main difference that I see between this, and other projects.
Webpack uses websockets and watches the project directory to intercept changes.

It's still unclear how these hours of activity are being recorded, while the computer is powered off! 

if I can give you more info, please let me know how, and where to find them. 

Cheers

**Comment by miwaniak** [comment]
Browser: Google Chrome 102.0.5005.115

Extensions:
- Angular DevTools 1.0.6
- DigitalPersona 3.0.0.905
- Google Docs Offline 1.44.2
- Headless Recorder 1.1.0
- HTML to Figma 0.0.5
- GNOME Shell 10.1
- JSONVue 0.1.17
- Lorem Ipsum Generator (Default Text) 2.4.0
- NordVPN – VPN Proxy for Privacy & Security 2.63.0
- React Developer Tools 4.24.7 (5/31/2022)
- Redux DevTools 3.0.11
- Saka 0.17.3
- Save to Pocket 4.0.5
- Google Mail Checker 4.4.0
- Vimium 1.67
- WakaTime 2.0.1
- Advanced REST client 10.0.12-stable

**Comment by jvelezpo** [comment]
closing this
there is new version of the extension that fixed this

duplicates https://github.com/wakatime/chrome-wakatime/issues/150
